"""Add s3 name column to meeting table

Revision ID: 0a2854580142
Revises: 76b5a73cc403
Create Date: 2024-08-18 19:57:01.107832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a2854580142'
down_revision = '76b5a73cc403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('s3_summary_name', sa.Text(), nullable=True))
        batch_op.drop_column('details')
        batch_op.drop_column('summary')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('s3_summary_name')

    # ### end Alembic commands ###
