"""Add payment status

Revision ID: 29544037b405
Revises: 650427f99ffb
Create Date: 2024-11-07 10:44:33.535036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29544037b405'
down_revision = '650427f99ffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
