"""Increase length for User table as well

Revision ID: 492c876a2f33
Revises: 8d77875147dd
Create Date: 2024-08-11 19:48:51.892694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '492c876a2f33'
down_revision = '8d77875147dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
