"""Added subscriber table

Revision ID: 53703e731af8
Revises: 72f9159498fd
Create Date: 2024-10-15 21:12:33.554404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53703e731af8'
down_revision = '72f9159498fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('subscribed_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribers')
    # ### end Alembic commands ###
