"""Add plan column for Organization

Revision ID: 650427f99ffb
Revises: 0f2e8e876d60
Create Date: 2024-11-07 10:31:43.050484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650427f99ffb'
down_revision = '0f2e8e876d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('plan')

    # ### end Alembic commands ###
