"""Add new fields to BotRecord model for webhook data

Revision ID: 71eef674a32c
Revises: f28af32ca499
Create Date: 2024-10-27 21:01:17.905300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71eef674a32c'
down_revision = 'f28af32ca499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sub_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('message', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('recording_id', sa.String(length=120), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_records', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('recording_id')
        batch_op.drop_column('message')
        batch_op.drop_column('sub_code')
        batch_op.drop_column('status_time')

    # ### end Alembic commands ###
