"""Add Calendar model

Revision ID: add61e3a9fb3
Revises: cccf04f34db9
Create Date: 2024-12-19 18:14:56.034487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add61e3a9fb3'
down_revision = 'cccf04f34db9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name='fk_calendar_org_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_calendar_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar')
    # ### end Alembic commands ###
