"""Remove meeting table and add invites

Revision ID: b3f347c976e8
Revises: f6d6ae8cd61c
Create Date: 2024-09-09 21:28:09.140344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b3f347c976e8'
down_revision = 'f6d6ae8cd61c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name='fk_user_organization_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('meeting')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('report_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('s3_summary_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], name='meeting_manager_id_fkey'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name='fk_user_organization_id'),
    sa.ForeignKeyConstraint(['report_id'], ['user.id'], name='meeting_report_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='meeting_pkey')
    )
    op.drop_table('invites')
    # ### end Alembic commands ###
