"""Add meeting name to bot record table

Revision ID: f28af32ca499
Revises: 6e71689c0637
Create Date: 2024-10-21 11:10:16.139615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f28af32ca499'
down_revision = '6e71689c0637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_name', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_records', schema=None) as batch_op:
        batch_op.drop_column('meeting_name')

    # ### end Alembic commands ###
